# Form implementation generated from reading ui file 'PS_UI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
#This file handles the creation and implementation of the MainWindow GUI where the user inputs data.

#Functionality includes an IP entry box, scan options, a port range, and an option to add OS detection.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 375)
        MainWindow.setMinimumSize(QtCore.QSize(350, 375))
        MainWindow.setMaximumSize(QtCore.QSize(350, 375))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.IP_Entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IP_Entry.setGeometry(QtCore.QRect(30, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.IP_Entry.setFont(font)
        self.IP_Entry.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.IP_Entry.setCursorPosition(0)
        self.IP_Entry.setClearButtonEnabled(False)
        self.IP_Entry.setObjectName("IP_Entry")
        self.input_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.input_label.setGeometry(QtCore.QRect(10, 10, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_label.setFont(font)
        self.input_label.setObjectName("input_label")
        self.scan_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.scan_button.setGeometry(QtCore.QRect(120, 260, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scan_button.setFont(font)
        self.scan_button.setObjectName("scan_button")
        self.SYN_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.SYN_radio.setGeometry(QtCore.QRect(0, 110, 111, 18))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.SYN_radio.setFont(font)
        self.SYN_radio.setObjectName("SYN_radio")
        self.UDP_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.UDP_radio.setGeometry(QtCore.QRect(120, 110, 83, 18))
        self.UDP_radio.setObjectName("UDP_radio")
        self.TCP_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.TCP_radio.setGeometry(QtCore.QRect(180, 110, 101, 18))
        self.TCP_radio.setObjectName("TCP_radio")
        self.scan_type_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.scan_type_label.setGeometry(QtCore.QRect(10, 80, 221, 20))
        self.scan_type_label.setObjectName("scan_type_label")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 111, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("scanGraphic.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.choose_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.choose_label.setGeometry(QtCore.QRect(10, 180, 201, 16))
        self.choose_label.setObjectName("choose_label")
        self.from_to_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.from_to_label.setGeometry(QtCore.QRect(10, 200, 181, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.from_to_label.setFont(font)
        self.from_to_label.setObjectName("from_to_label")
        self.port1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port1.setGeometry(QtCore.QRect(50, 200, 61, 20))
        self.port1.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.port1.setCursorPosition(0)
        self.port1.setObjectName("port1")
        self.port2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.port2.setGeometry(QtCore.QRect(150, 200, 61, 20))
        self.port2.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.port2.setCursorPosition(0)
        self.port2.setObjectName("port2")
        self.idle_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.idle_radio.setGeometry(QtCore.QRect(30, 140, 111, 18))
        self.idle_radio.setObjectName("idle_radio")
        self.ping_radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.ping_radio.setGeometry(QtCore.QRect(150, 140, 111, 18))
        self.ping_radio.setObjectName("ping_radio")
        self.os_scan_check = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.os_scan_check.setGeometry(QtCore.QRect(10, 230, 191, 18))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.os_scan_check.setFont(font)
        self.os_scan_check.setObjectName("os_scan_check")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(120, 300, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 100))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Nmap Scan"))
        self.IP_Entry.setInputMask(_translate("MainWindow", "000.000.000.000"))
        self.IP_Entry.setText(_translate("MainWindow", "..."))
        self.IP_Entry.setPlaceholderText(_translate("MainWindow", "___.___.___.___"))
        self.input_label.setText(_translate("MainWindow", "Enter an IPv4 Address Below:"))
        self.scan_button.setText(_translate("MainWindow", "Scan"))
        self.SYN_radio.setText(_translate("MainWindow", "SYN(Stealthiest)"))
        self.UDP_radio.setText(_translate("MainWindow", "UDP"))
        self.TCP_radio.setText(_translate("MainWindow", "TCP Connect"))
        self.scan_type_label.setText(_translate("MainWindow", "Choose a Scan Type Below:"))
        self.choose_label.setText(_translate("MainWindow", "Choose a range of ports to scan:"))
        self.from_to_label.setText(_translate("MainWindow", "From:                    To:"))
        self.port1.setInputMask(_translate("MainWindow", "00000"))
        self.port2.setInputMask(_translate("MainWindow", "00000"))
        self.idle_radio.setText(_translate("MainWindow", "IDLE(Spoofs IP)"))
        self.ping_radio.setText(_translate("MainWindow", "PING(Fastest)"))
        self.os_scan_check.setText(_translate("MainWindow", "Scan for Operating System?"))
        self.label_2.setText(_translate("MainWindow", "Please Fill in All Values"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
